### ISSUE TITLE
created another solution for this problem

### ISSUE THREAD

**Issue by odedniv** [JacobFischer/sync-socket#2]
Thought you may want to look at another solution for the sync socket problem (I've seen you had 2): https://www.npmjs.com/package/csocket

Let me know what you think.

**Comment by JacobFischer** [comment]
That's really cool. However your project has the native dependencies to build, where-as my module here has **no dependencies**. It was important to me that this module required nothing more than Node, as in the environments this was created for native modules could not build (locked down Windows installs).

Also, I have another package, [netlinkwrapper](https://www.npmjs.com/package/netlinkwrapper), that is also a synchronous socket implementation that uses native dependencies. In my case the C++ library netlink is built. It's by no means elegant or amazing, but it gets the job done.

You highlight in your readme that synchronous reads to a socket is a bad idea, and really no one should be using our solutions. That is something that I think is brilliant, and I should probably highlight that in mine more. Perhaps your native solution is better than mine and I may migrate my projects that use your module.

I'm going to close this issue because it's not really an issue with this module. However if anyone wants to comment on sync-socket or migrating to csocket feel free to comment in this issue, or make a new one.

Thanks again for the heads up!

**Comment by odedniv** [comment]
I saw netlinkwrapper as well, thinking about it now maybe it was more appropriate to notify you about csocket there rather than here.

I had two issues with netlinkwrapper:
1. It doesn't expose server methods (listen, bind, accept). In csocket I tried to do as little as possible while still allowing everything possible in C.
2. It doesn't expose the file descriptor. Like you wrote, using this is a bad idea, which is why I want the user (aka me) to only use where required, sometimes even only partially. This is why exposing the file descriptor is important - you can use it in order to continue working with native async node functions (e.g `fs.read` and `net.Socket`) by supplying the file descriptor to them - and then stop using `csocket`.

An example use case is that I want to bind+listen synchronously (e.g before spawning a process that is supposed to connect to this socket), while the rest of the socket usage (accept, read/write) can switch back to asynchronous implementation using `net.Socket`. Check out the bottom of the readme about that.

I agree with closing this, opened the issue to let you know, this is not a real issue.
